# Generated by Django 4.1.2 on 2022-10-14 10:56

import django.core.validators
from django.db import migrations, models
import fileupload.models


class Migration(migrations.Migration):

    dependencies = [
        ("fileupload", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileuploader",
            name="upload_dir",
            field=models.FileField(
                upload_to=fileupload.models.dir_path_name,
                validators=[django.core.validators.FileExtensionValidator(["csv"])],
            ),
        ),
    ]
