# Generated by Django 4.1.2 on 2022-10-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fileupload", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileuploader",
            name="title",
            field=models.CharField(default="CSVファイル", max_length=50),
        ),
    ]
