# Generated by Django 4.1.3 on 2022-11-15 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fileupload", "0002_alter_fileuploader_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageFileUploader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="img/")),
            ],
        ),
    ]
