# Generated by Django 4.1.2 on 2022-10-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fileupload", "0002_alter_fileuploader_upload_dir"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileuploader",
            name="title",
            field=models.CharField(default="CSVファイル", max_length=50),
        ),
    ]
